### ISSUE TITLE
Limit tags that can be entered

### ISSUE THREAD

**Issue by jbrooksuk** [sambenne/jQuery-Tags-Input#2]
I implemented this real quick, but it's a handy, especially when you could merge it with auto completion. I'll push the changes tomorrow.

**Comment by sambenne** [comment]
I have added the limit. I was thinking whether creating my own auto complete or just use jQuery UI. What do you think?

**Comment by jbrooksuk** [comment]
I'd advise that you create your own, similar to how Chosen works - with the list of `li` elements. The complete URL is just an AJAX request returning some JSON.

Look at how Chosen filters down results via regular expressions.

**Comment by sambenne** [comment]
Right I am starting to work on it now.

**Comment by sambenne** [comment]
I have added it in. I am going to work on the autocomplete url one a bit more.
